<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.18435628 0.65255458 0.37623361 ... 0.89387172 0.00767365 0.29270679]
 [0.96642623 0.09938168 0.87883329 ... 0.72158102 0.50408465 0.08131674]
 [0.5723234  0.07211461 0.97944534 ... 0.0202035  0.67525182 0.34702387]
 ...
 [0.6528494  0.0611689  0.85955981 ... 0.15333231 0.09199014 0.20944276]
 [0.75328673 0.60737771 0.64436993 ... 0.10219758 0.42440052 0.40107247]
 [0.50061095 0.21879012 0.08729822 ... 0.84798956 0.73612551 0.75160288]]
[[0.45535017 0.01833659 0.52919926 ... 0.64278783 0.77085885 0.22938528]
 [0.66395811 0.5401138  0.79938081 ... 0.426592   0.74823564 0.61179653]
 [0.58437632 0.5698077  0.99405156 ... 0.41084268 0.74900968 0.72860268]
 ...
 [0.56760964 0.17589702 0.23709455 ... 0.12249393 0.94068936 0.42521076]
 [0.91777555 0.58647302 0.42001046 ... 0.6387367  0.22726602 0.06447552]
 [0.0980953  0.42571457 0.87585272 ... 0.6769894  0.88479742 0.02805623]]


In [3]:
def mult(a, b):
    """
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    n = len(a)
    res_matrix = [[0 for i in range(n)] for j in range(n)]

    for i in range(n):
      for j in range(n):
        for z in range(n):
            res_matrix[i][j] += (a[i][z] * b[z][j])
    return res_matrix

In [4]:
def np_mult(a, b):
    """
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a.dot(b)

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.19 s, sys: 4.32 ms, total: 1.2 s
Wall time: 1.74 s


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.74 ms, sys: 4.15 ms, total: 6.89 ms
Wall time: 13.3 ms


In [7]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.44783045 0.59740689 0.3590454 ] [0.58412278 0.90241985 0.52457271]


In [9]:
def scalar_product(a, b):
    """
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

In [10]:
def np_scalar_product(a,b):
    """
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    a = np.array(a)
    b = np.array(b)
    return a.dot(b)

In [11]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 52 µs, sys: 0 ns, total: 52 µs
Wall time: 58.4 µs
CPU times: user 2.91 ms, sys: 1.84 ms, total: 4.75 ms
Wall time: 5.23 ms


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [12]:
def np_diag_2k(a):
    """
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    return sum(np.diagonal(a)[np.diagonal(a)%2 == 0])

In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 4, 2, 3, 7],
       [7, 6, 8, 8, 6],
       [2, 2, 4, 7, 9],
       [6, 3, 4, 5, 3],
       [9, 3, 6, 8, 4]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 127 µs, sys: 19 µs, total: 146 µs
Wall time: 154 µs


22

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [15]:
def cumsum(A):
    """
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    return np.cumsum(A, axis=-1)

In [16]:
# зададим некоторую последовательность и проверим ее на вашей функции.
A = sps.uniform.rvs(size=10**3)

%time S2 = cumsum(A)

CPU times: user 77 µs, sys: 0 ns, total: 77 µs
Wall time: 83.9 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [17]:
from copy import copy
def np_transformation(X, a=1):
    """
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке,
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    Y = X.copy()
    Y[:, 1::2] = a
    Y[:, 0::2] = Y[:,0::2]**3
    Y = Y[:, ::-1]
    return np.hstack((X, Y))

In [18]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 185 µs, sys: 28 µs, total: 213 µs
Wall time: 192 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [34]:
import itertools

def np_encode(a):
    """
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор
    repetitions добавляет длины последовательностей подряд идущих повторений.
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    return [(x, list(y)) for x, y in itertools.groupby(X)]

In [36]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time num = np_encode(X)

CPU times: user 32 µs, sys: 4 µs, total: 36 µs
Wall time: 41 µs
